# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
gems:                [jekyll-paginate]

# Setup
title:               Pixxel
tagline:             'Marcos Gutierrez'
description:         'Web developer de CÃ³rdoba, Argentina. Codeando desde el medio de las sierras siempre que interent ayude'
url:                 https://gmarcos87.github.io/pixxel.com.ar
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Marcos Gutierrez
  url:               https://twitter.com/jsPixxel
  email:             mg@pixxel.com.ar

# Custom vars
version:             1.0.0
